before_build:
  - nuget restore

configuration:
  - Release

build:
  project: RestProcessor.sln

artifacts:
  - path: RestProcessor
    name: RestProcessorArtifacts
    type: zip

on_success:
  - foreach ($artifactName in $artifacts.keys) {
        echo $artifacts[$artifactName].url
    }
