image: Visual Studio 2017
before_build:
  - nuget restore

configuration:
  - Release

build:
  project: RestApi.sln

artifacts:
  - path: RestProcessor\bin\$(configuration)
    name: RestProcessorArtifacts
    type: zip