before_build:
  - nuget restore

configuration:
  - Release

build:
  project: RestApi.sln

artifacts:
  - path: Microsoft.RestApi.RestCI\bin\$(configuration)
    name: RestProcessorArtifacts
    type: zip
